### ISSUE TITLE
Change default options / save settings

### ISSUE THREAD

**Issue by BndlfLeGlnd** [oleg-st/InvertMouse#6]
Hello !
Is there an option to save the last settings or edit default settings on program launch please?
I'd like InvertMouse to start with Y and X axis inverted.

Thank you very much !

**Comment by oleg-st** [comment]
Hello,
Good suggestion, I'll add this

**Comment by oleg-st** [comment]
Done in 1.0.4

**Comment by BndlfLeGlnd** [comment]
works like a charm, thank you very much !
