### ISSUE TITLE
Can the ms delay be modified?

### ISSUE THREAD

**Issue by Guthaes** [oleg-st/InvertMouse#9]
Us old school PC players playing ported mobile games to PC absolutely love this app.  However, when playing shooters, when the mouse cursor appears, we have to wait a full second for it to kick in, which can get us killed.  Is there any way to have an option to change the millisecond time?  1000ms doesn't seem like a long time but it does affect players in FPS games.

**Comment by oleg-st** [comment]
The delay comes from the Raw Accel driver, you can use the Interception driver, it has no delay.
